export const metadata = {
  title: "About Us",
};

export default function AboutUsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="container">
      {children}
      <footer>&copy; generated by layout</footer>
    </div>
  );
}
